version: "3.9"

services:
    cs2c-rabbitmq:
        image: rabbitmq:3-management
        container_name: cs2c-rabbitmq
        ports:
            - "5672:5672" # AMQP
            - "15672:15672" # Management UI
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest

    cs2c-apiserver:
        build: ./apiserver
        container_name: cs2c-apiserver
        ports:
            - "8080:8080"
        volumes:
            - ./apiserver:/app # mount source
        environment:
            ENV: prod
            RABBITMQ_URL: amqp://guest:guest@cs2c-rabbitmq:5672/
            STORE_DEMO_PATH: ./demo_store
        depends_on:
            - cs2c-rabbitmq
        # command: sh -c "air" # or another live reload tool
        command: go run main.go

    cs2c-parsingservice:
        build: ./parsingservice
        container_name: cs2c-parsingservice
        volumes:
            - ./parsingservice:/app
        environment:
            ENV: prod
            RABBITMQ_URL: amqp://guest:guest@cs2c-rabbitmq:5672/
            STORE_DEMO_PATH: ./demo_store
        depends_on:
            - cs2c-rabbitmq
            - cs2c-apiserver
        # command: sh -c "air"
        command: go run main.go
