version: "3.9"

name: c2sc-backend

services:
    cs2c-rabbitmq:
        image: rabbitmq:3-management
        container_name: cs2c-rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest

    cs2c-apiserver:
        build: ./apiserver
        container_name: cs2c-apiserver
        ports:
            - "8080:8080"
        volumes:
            - ./apiserver:/app
            - demo_store:/app/demo_store
        environment:
            ENV: prod
            RABBITMQ_URL: amqp://guest:guest@cs2c-rabbitmq:5672/
            STORE_DEMO_PATH: app/demo_store
        depends_on:
            - cs2c-rabbitmq
        command: go run main.go

    cs2c-parsingservice:
        build: ./parsingservice
        container_name: cs2c-parsingservice
        volumes:
            - ./parsingservice:/app
            - demo_store:/app/demo_store
        environment:
            ENV: prod
            RABBITMQ_URL: amqp://guest:guest@cs2c-rabbitmq:5672/
            STORE_DEMO_PATH: app/demo_store
        depends_on:
            - cs2c-rabbitmq
            - cs2c-apiserver
        command: go run main.go

    cs2c-database:
        image: postgres:15
        container_name: cs2c-database
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: cs2c
            POSTGRES_PASSWORD: cs2c
            POSTGRES_DB: cs2c
        volumes:
            - database:/var/lib/postgresql/data

volumes:
    demo_store: